In [47]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


# Introduction to tensors
##Creating tensors
  


In [48]:
vector = torch.tensor([2,4])

In [49]:
vector.shape

torch.Size([2])

In [50]:
matrix = torch.tensor([[7,8],[1,2]])

###Random Tensors

In [51]:
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.3347, 0.7285, 0.5794],
        [0.4946, 0.9831, 0.5134],
        [0.2580, 0.5002, 0.6152]])

###Zeros and Ones

In [52]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size =(3,4))

##Creating range of tensors and tensor-like

In [53]:
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [54]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1])

##Tensor Datatypes

In [55]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [56]:

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

## Manipulating tensor


In [57]:
# Create tensor

In [58]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [59]:
tensor*10

tensor([10, 20, 30])

In [60]:
tensor -10

tensor([-9, -8, -7])

In [61]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [62]:
tensor*tensor #element wise

tensor([1, 4, 9])

In [63]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 95 µs, sys: 0 ns, total: 95 µs
Wall time: 101 µs


tensor(14)

In [64]:
tensor2 = torch.rand(3,5)
tensor2

tensor([[0.6283, 0.6972, 0.5420, 0.5651, 0.0891],
        [0.8486, 0.1901, 0.3035, 0.6512, 0.4057],
        [0.8156, 0.6753, 0.9405, 0.6498, 0.6329]])

In [65]:
tensor2.T

tensor([[0.6283, 0.8486, 0.8156],
        [0.6972, 0.1901, 0.6753],
        [0.5420, 0.3035, 0.9405],
        [0.5651, 0.6512, 0.6498],
        [0.0891, 0.4057, 0.6329]])

In [66]:
x = torch.arange(1,101,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [67]:
x.min()

tensor(1)

In [68]:
torch.max(x)

tensor(91)

In [69]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [70]:
torch.sum(x)

tensor(460)

In [71]:
torch.argmin(x)

tensor(0)

In [72]:
x.argmax()

tensor(9)

In [73]:
x_reshaped = x.reshape(10,1)
x_reshaped

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

In [74]:
x_Viewed = x.view(10,1)
x_Viewed

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

Changing x_viewed also changes the x tensor coz they share the same memory

In [75]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [76]:
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked

tensor([[ 1,  1,  1,  1],
        [11, 11, 11, 11],
        [21, 21, 21, 21],
        [31, 31, 31, 31],
        [41, 41, 41, 41],
        [51, 51, 51, 51],
        [61, 61, 61, 61],
        [71, 71, 71, 71],
        [81, 81, 81, 81],
        [91, 91, 91, 91]])

In [77]:
x_reshaped

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

In [78]:
y = torch.squeeze(x_reshaped)
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

It removes the dimension of size 1

In [79]:
torch.unsqueeze(y,dim=1)

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

It adds a dimenssion

In [80]:
x = torch.rand(size=[224,224,3])
x_permute = x.permute(2,0,1)
x_permute.shape

torch.Size([3, 224, 224])

Its a view and thus shares the same memory as the original

In [81]:
#create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)

In [82]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [84]:

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [85]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cpu'

In [86]:
# Count number of devices
torch.cuda.device_count()

0

In [87]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [88]:
# If tensor is on GPU, can't transform it to NumPy
 #(this will error)
tensor_on_gpu.numpy()

array([1, 2, 3])

In [89]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])