In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu118


# Introduction to tensors
##Creating tensors
  


In [2]:
vector = torch.tensor([2,4])

In [3]:
vector.shape

torch.Size([2])

In [4]:
matrix = torch.tensor([[7,8],[1,2]])

###Random Tensors

In [5]:
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.5708, 0.9619, 0.1366],
        [0.8724, 0.5262, 0.1898],
        [0.2692, 0.7292, 0.0453]])

###Zeros and Ones

In [6]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size =(3,4))

##Creating range of tensors and tensor-like

In [9]:
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [13]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1])

##Tensor Datatypes

In [18]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [19]:

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

## Manipulating tensor


In [ ]:
# Create tensor

In [21]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [22]:
tensor*10

tensor([10, 20, 30])

In [23]:
tensor -10

tensor([-9, -8, -7])

In [24]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [25]:
tensor*tensor #element wise

tensor([1, 4, 9])

In [27]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 584 µs, sys: 0 ns, total: 584 µs
Wall time: 480 µs


tensor(14)

In [30]:
tensor2 = torch.rand(3,5)
tensor2

tensor([[0.6726, 0.6595, 0.8482, 0.0768, 0.3188],
        [0.4462, 0.5512, 0.5557, 0.6437, 0.7317],
        [0.9450, 0.2106, 0.7160, 0.0775, 0.3683]])

In [31]:
tensor2.T

tensor([[0.6726, 0.4462, 0.9450],
        [0.6595, 0.5512, 0.2106],
        [0.8482, 0.5557, 0.7160],
        [0.0768, 0.6437, 0.0775],
        [0.3188, 0.7317, 0.3683]])

In [47]:
x = torch.arange(1,101,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [48]:
x.min()

tensor(1)

In [49]:
torch.max(x)

tensor(91)

In [50]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [51]:
torch.sum(x)

tensor(460)

In [53]:
torch.argmin(x)

tensor(0)

In [54]:
x.argmax()

tensor(9)

In [57]:
x_reshaped = x.reshape(10,1)
x_reshaped

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

In [65]:
x_Viewed = x.view(10,1)
x_Viewed

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

Changing x_viewed also changes the x tensor coz they share the same memory

In [67]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [68]:
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked

tensor([[ 1,  1,  1,  1],
        [11, 11, 11, 11],
        [21, 21, 21, 21],
        [31, 31, 31, 31],
        [41, 41, 41, 41],
        [51, 51, 51, 51],
        [61, 61, 61, 61],
        [71, 71, 71, 71],
        [81, 81, 81, 81],
        [91, 91, 91, 91]])

In [70]:
x_reshaped

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

In [74]:
y = torch.squeeze(x_reshaped)
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

It removes the dimension of size 1

In [78]:
torch.unsqueeze(y,dim=1)

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

It adds a dimenssion

In [82]:
x = torch.rand(size=[224,224,3])
x_permute = x.permute(2,0,1)
x_permute.shape

torch.Size([3, 224, 224])

Its a view and thus shares the same memory as the original

In [86]:
#create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)